import Database from "better-sqlite3";
import { mkdirSync, readFileSync } from "node:fs";
import { join } from "node:path";
import type { CanonicalConversation, CanonicalThread, TargetPaths } from "../src/core/types.js";
import { resolveTargetPaths } from "../src/target/config.js";

/** Schemas generated by the pinned upstream migration runners, not handwritten SQL. */
export function createTarget(root: string, migration = 40): TargetPaths {
  const schemas = JSON.parse(readFileSync(new URL("./fixtures/t3-schemas.json", import.meta.url), "utf8")) as Record<string, { ddl: string[]; migrations: Array<Record<string, string | number>> }>;
  const schema = schemas[String(migration)] ?? schemas["40"]!;
  const paths = resolveTargetPaths({ t3Home: root });
  mkdirSync(paths.stateDir, { recursive: true });
  const db = new Database(paths.dbPath);
  try {
    // Fixture setup is atomic; avoid a disk sync per table/index/migration row
    // when exercising the complete historical schema on slower CI runners.
    db.transaction(() => {
      db.exec(schema.ddl.join(";\n"));
      for (const row of schema.migrations) {
        const columns = Object.keys(row);
        db.prepare(`INSERT INTO effect_sql_migrations (${columns.join(", ")}) VALUES (${columns.map(() => "?").join(", ")})`).run(...Object.values(row));
      }
      // Unsupported versions are only used to exercise fail-closed validation.
      if (!schemas[String(migration)]) {
        db.prepare("DELETE FROM effect_sql_migrations WHERE migration_id = ?").run(migration);
        db.prepare("UPDATE effect_sql_migrations SET migration_id = ? WHERE migration_id = 40").run(migration);
      }
    })();
  } finally { db.close(); }
  return paths;
}

export function canonicalThread(workspace: string): CanonicalThread {
  return {
    source: "codex",
    sourceSessionId: "11111111-1111-4111-8111-111111111111",
    sourceKey: "codex:11111111-1111-4111-8111-111111111111",
    currentBranch: true,
    title: "Fixture task",
    workspace,
    model: "gpt-test",
    effort: "high",
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:03.000Z",
    turns: [{
      id: "turn-1",
      startedAt: "2026-01-01T00:00:00.000Z",
      completedAt: "2026-01-01T00:00:03.000Z",
      status: "completed",
      user: { sourceId: "user-1", role: "user", text: "Hello", timestamp: "2026-01-01T00:00:00.000Z", attachments: [] },
      assistant: [{ sourceId: "assistant-1", role: "assistant", text: "Hi", timestamp: "2026-01-01T00:00:02.000Z", attachments: [] }],
      activities: [{ sourceId: "tool-1", tone: "tool", kind: "tool.completed", summary: "Command", timestamp: "2026-01-01T00:00:01.000Z", payload: { itemType: "command_execution", status: "completed", data: { item: { command: "pwd" } } } }],
      plans: [],
    }],
    resumeCursor: { threadId: "11111111-1111-4111-8111-111111111111" },
    warnings: [],
  };
}

export function canonicalConversation(workspace: string, thread = canonicalThread(workspace)): CanonicalConversation {
  return {
    summary: { source: thread.source, id: thread.sourceSessionId, title: thread.title, workspace, path: "fixture.jsonl", createdAt: thread.createdAt, updatedAt: thread.updatedAt, status: "complete", branches: 1 },
    threads: [thread],
    fingerprint: "fixture-fingerprint",
  };
}

export function eventCount(path: string): number {
  const db = new Database(path, { readonly: true });
  try { return (db.prepare("SELECT COUNT(*) count FROM orchestration_events").get() as { count: number }).count; }
  finally { db.close(); }
}
